services:
  wordpress:
    container_name: wordpress
    image: wordpress:1.0.0
    build: ./requirements/wordpress/
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_wordpress:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception

  mariadb:
    container_name: mariadb
    image: mariadb:1.0.0
    env_file: .env
    build: ./requirements/mariadb/
    volumes:
      - db_mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - inception
  nginx:
    container_name: nginx
    image: nginx:1.0.0
    build: ./requirements/nginx/
    env_file: .env
    restart: unless-stopped
    volumes:
      - db_wordpress:/var/www/html
    depends_on:
      - wordpress
      - portainer
    ports:
      - 443:443
    networks:
      - inception

  redis:
    container_name: redis
    image: redis:1.0.0
    build: ./requirements/redis/
    env_file: .env
    restart: unless-stopped
    depends_on:
      - wordpress
    volumes:
      - db_wordpress:/var/www/html
    networks:
      - inception
    
  fpt-server:
    container_name: ftp-server
    image: ftp-server:1.0.0
    build: ./requirements/ftp-server
    env_file: .env
    restart: unless-stopped
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
    - db_wordpress:/var/www/html
    networks:
    - inception
  
  adminer:
    container_name: adminer
    image: adminer:1.0.0
    build: ./requirements/adminer
    expose:
      - "9000"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      - inception

  portainer:
    container_name: portainer
    image: portainer:1.0.0
    build: ./requirements/portainer
    env_file: .env
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - "9000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    networks:
      - inception

volumes:
  db_mariadb:
    name: db_mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_DATA_LOCATION}
  db_wordpress:
    name: db_wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_DATA_LOCATION}

networks:
  inception:
    name: inception
    driver: bridge