services:
 wordpress:
  container_name: wordpress
  build: ./requirements/wordpress
 mariadb:
  container_name: mariadb
  build: ./requirements/mariadb
 nginx:
  container_name: nginx
  build: ./requirements/nginx/
  env_file: .env
  ports:
      - 443:443
  networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_DATA_LOCATION}
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_DATA_LOCATION}

networks:
 inception:
  name: inception