services:
 wordpress:
  container_name: wordpress
  image: wordpress:1.0.0
  build: ./requirements/wordpress/
  env_file: .env
  depends_on:
    - mariadb
  networks:
    - inception
 mariadb:
  container_name: mariadb
  image: mariadb:1.0.0
  env_file: .env
  build: ./requirements/mariadb/
  networks:
      - inception
 nginx:
  container_name: nginx
  image: nginx:1.0.0
  build: ./requirements/nginx/
  env_file: .env
  depends_on:
    - wordpress
  ports:
    - 443:443
  networks:
    - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARIADB_DATA_LOCATION}
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${WORDPRESS_DATA_LOCATION}

networks:
 inception:
  name: inception