FROM debian:bullseye

# Actualizar paquetes e instalar dependencias necesarias
RUN apt update -y && apt upgrade -y \
    && apt install -y nginx openssl curl gnupg2 apt-transport-https ca-certificates software-properties-common \
    && apt clean && rm -rf /var/lib/apt/lists/*

# Exponer el puerto de Nginx (si es necesario)
EXPOSE 80

# Iniciar Nginx en primer plano
CMD ["nginx", "-g", "daemon off;"]